import 
import "./app.css";
import { notePreset } from "@tonaljs/tonal";
preset: notePreset.beatbox,
    color: "black",
    width: 200,
    height: 100,
    barWidth: 1,
    barHeight: 50,
    barSpacing: 2,
    barGap: 1,
    barFillStyle: "black",
    barBackgroundColor: "white",
    barShadowColor: "white",
    barShadowBlur: 5,
    barShadowOffsetX: 2,
    barShadowOffsetY: 2,
    barTransition: "ease-in-out",
    barAnimationDuration: 500,
    barAnimationDelay: 0,
    barAnimationEasing: "linear",
    barAnimationReverse: false,
    barAnimationLoop: true,
    barAnimationDirection: "up",
    barAnimationColor: "black",
    barAnimationBackgroundColor: "white",
    barAnimationShadowColor: "white",
    barAnimationShadowBlur: "none",